import { type Settings } from "./types";

export const mergeDefaults = (settings: Partial<Settings>): Settings => {
  return {
    text: '',
    w: 0,
    h: 0,
    fontStyle: 'normal',
    fontSize: 40,
    fontFamily: null,
    trFontFace: null,
    wordWrap: true,
    wordWrapWidth: 0,
    wordBreak: false,
    textOverflow: '',
    lineHeight: null,
    textBaseline: 'alphabetic',
    textAlign: 'left',
    verticalAlign: 'top',
    offsetY: null,
    maxLines: 0,
    maxHeight: null,
    overflowSuffix: '...',
    textColor: [1.0, 1.0, 1.0, 1.0],
    paddingLeft: 0,
    paddingRight: 0,
    shadow: false,
    shadowColor: [0.0, 0.0, 0.0, 1.0],
    shadowOffsetX: 0,
    shadowOffsetY: 0,
    shadowBlur: 5,
    highlight: false,
    highlightHeight: 0,
    highlightColor: [0.0, 0.0, 0.0, 1.0],
    highlightOffset: 0,
    highlightPaddingLeft: 0,
    highlightPaddingRight: 0,
    letterSpacing: 0,
    textIndent: 0,
    cutSx: 0,
    cutEx: 0,
    cutSy: 0,
    cutEy: 0,
    advancedRenderer: false,
    fontBaselineRatio: 0,
    precision: 1,
    textRenderIssueMargin: 0,
    ...settings,
  };
}
